name: pawfuel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.10.0
  webview_flutter_wkwebview: 3.20.0


dependency_overrides:
  webview_flutter_wkwebview: 3.23.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/www/index.html
    - assets/www/

# Launcher icons config
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
